workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons

      - name: Build App Bundle
        script: flutter build appbundle --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
